---
title: "Defining Outputs"
format: html
toc: true
editor: source
---
## Session Overview

### Learn

We will spend time reviewing your proposed final outputs from your capstone project or thesis.

### Reflect

We will workshop your proposed audience and their communication needs and goals.

### Review

We will develop idea boards that represent some of the key elements of your proposed capstone outputs.

## Before we Meet

Come to class prepared to share with each other the following:

1. The main goals and objectives of your capstone

2. The target audience for your capstone

3. The approach you plan to take

4. The types of key findings or recommendations that are likely to result

5. Ideas or examples of outputs like those you intend to create that will best communicate and create impact from your work

## After we Meet

Complete your capstone idea boards and continue to curate and modify them over time. Be ready to share during our next session.

## Additional Resources

[Djordje Takov Capstone](https://www.ideals.illinois.edu/items/119517) / [Video](https://www.youtube.com/watch?v=HCagIWeL9bE&t=6s)

[J.D. McClanahan Capstone](https://uofi.app.box.com/s/1yetl9gf21w12pe6w10nrlacob2zoet8) / [Video](https://mediaspace.illinois.edu/media/t/1_lu7lflpk/208001093)