---
title: "End of Semester Check-In"
format: html
toc: true
editor: source
---

## Session Overview

As we conclude our work in UP 591 for the fall semester, we will provide a major update to each other on our capstone progress and deliverables. Our session will be spent sharing these updates with each other.

## Before we Meet

Prepare a 4-slide presentation summarizing your professional identity. 

**Slide 1:** Overview - describe your overall professional identity including 2 or 3 defining features of your approach to work and your vision for impact.

**Slide 2:** Past Training and Experiences - describe the contributions of your past education, training, and work experiences to your professional identity.

**Slide 3:** Present Work - share some of the highlights of the projects you're working on at present that are reflective of your professional identity.

**Slide 4:** Future Career Goals and Objectives - describe your future career goals and vision for employment steps after you complete your MUP degree.

## When we Meet

Presentation order (to be determined).

## After we Meet

Think about how you plan to tell the story of your evolution as a professional as part of your portfolio which is due in the spring.

Think critically about how you will complete your workshop, project, or thesis deliverables. If something you originally proposed is now no longer feasible, now is an important time to communicate this to your instructor, client, or advisor.

For those of you pursuing the project or thesis options, please share a substantive capstone update with your project / thesis adviser before the end of the semester.

## Additional Resources
