---
title: "Workshop and Capstone Pathway Adoption"
format: html
toc: true
sidebar: true
editor: source
---

## Deliverable Overview

In the spring semester before your second year, you will identify which capstone pathway you plan to pursue and will share your preferences for which workshop courses you will take in your second year.

## Capstone Pathways

There are three pathways to satisfy the practice component of the MUP capstone requirement. By default, you are expected to pursue the Plan Making Workshop pathway. Students wishing to pursue the Project Pathway or Thesis Pathway need to describe their projects and petition to adopt an alternate pathway.

**Plan Making Workshop:** Exposure to professional planning practice by completing two plan making workshops. The audience for the projects completed in these workshops is typically planning and policy practitioners and decision makers. Faculty workshop leaders work in partnership with an institution, organization, or community partner to determine the scope and deliverables from the workshop in advance. Typical workshop deliverables may be a report, a plan, or other professional quality work.

**Master's Project:** A professional project or analysis focusing on a topic relevant to the student's selected concentration and career goals. The audience for a master’s project is typically planning and policy practitioners and decisionmakers. The capstone deliverable may be a report, a plan, or other professional quality work. The project is conducted for or with an external client.

**Masters Thesis:** A scholarly applied or basic research work conducted under the formal Thesis Guidelines of the Department and Graduate College. The audience for a master’s thesis is typically academic and applied researchers. The thesis option is most appropriate for MUP students with a strong interest in pursuing a research-oriented career or PhD degree.

## Pathway Documentation

One of your first tasks is to "adopt" your capstone project. You will do this in the spring before your second year by completing the [following form](https://forms.illinois.edu/sec/1915761140) to indicate your capstone pathway and preferences regarding workshop offerings.

### Additional Documentation for Projects and Theses

- For the **Project Pathway** you need to share a detailed description of your projects subject and scope, a description of your client, and need to secure the signature of your client and the faculty member who has agreed to supervise your project.

- For the **Thesis Pathway** you need to share a project abstract and need to secure the signature of your thesis advisor and a second faculty committee member. You should have also shared a detailed proposal with both your thesis adviser and your other committee member by the time you adopt your capstone.

## Milestone Deliverable

If you pursue the Workshop pathway, the only needed documentation is the submission of the pathway adoption web form. For those who are petitioning to adopt the project or thesis pathway, please complete the [Capstone Adoption Form](files/02_CapstoneAdoption.pdf), including all required signatures (based upon the capstone pathway you are pursuing) and submit to the file dropbox below.

## Resources

- [Capstone Adoption Form](files/02_CapstoneAdoption.pdf)

## Submission Instructions

All capstone pathways will complete the capstone adoption [web form](https://forms.illinois.edu/sec/1915761140) to indicate the proposed capstone pathway and preferences regarding workshop offerings.

Individuals pursuing the **project** or **thesis** pathways must subsequently submit the PDF Capstone Adoption Form with all required signatures to petition into these alternate pathways. The initial submission should be made using the below file dropbox:

<iframe src="https://uofi.app.box.com/f/5affe018728548b485e246d2d755e0b4" height="900" width="800"></iframe>